apiVersion: apps/v1
kind: Deployment
metadata: 
  name: housing-prediction-ml
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: fast-api
  template:
    metadata:
      labels:
        app: fast-api

    spec: 
      containers:
      - name: housing-prediction-ml
        image: kaushiktd/housing_prediction
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports: 
          - containerPort: 9001

---
apiVersion: v1
kind: Service
metadata:
  name: fast-api-service
spec:
  selector:
    app: fast-api
  ports:
  - port: 9001
    targetPort: 9001
  type: LoadBalancer          

              